hellohaptik/docs_haptik

bot-configuration/webhooks.md

update curl command

---

bot-configuration/webhooks.md

update doc to include webhook retry logic

webhook retry logic doc

---

bot-configuration/webhooks.md

update webhook docs

---

docs/bot-configuration/webhooks.md

Update webhook docs (docusaurus)

---

bot-configuration/webhooks.md

update webhook docs (readthedocs)

---

docs/bot-builder/basic/making-first-bot.md
website/siteConfig.js

Update CNAME to documentation to docs.haptik.ai
Needed updating URLs on haptik website 
will update siteConfig.js and making-first-bot.md

Cname update

---

website/pages/en/index.js

Updated CTAs for SDK Integrations

---

docs/agent-chat/meta.json
docs/bot-analytics/meta.json

Fixing the incorrect folder structure and meta.json files

Fix meta files for Athena and Analytics

---

docs/bot-analytics/story-analysis.md
docs/bot-analytics/user-journey.md
docs/bot-builder/basic/bot-hierarchy.md
docs/bot-builder/basic/bot-prompt-trigger.md
docs/bot-builder/basic/creating-story.md
docs/bot-builder/basic/making-first-bot.md
docs/bot-builder/basic/multiple-languages.md

Update image paths for Story ANalysis page of Analytics tool

---

docs/bot-builder/advanced/integrating-custom-code.md

Fix indentation in sample code

---

docs/agent-chat/action-toolbars.md
docs/agent-chat/smart-actions.md

Smart actions and action toolbar were in the same file. But as per the LHS structure, they should have been different.

Reorganize smart actions and action toolbar

---

docs/webhooks/api-security-rules.md
docs/webhooks/create-haptik-user.md
docs/webhooks/index.md
docs/webhooks/protocols.md
docs/webhooks/re-enable-webhook.md
docs/webhooks/rules-webhook-creation.md
docs/webhooks/send-image-to-haptik.md
docs/webhooks/send-message-to-haptik.md
docs/webhooks/webhook-payload.md

to remove typos and improve the formatting for webhook documentation
ADHOC
TODO - Remove URLs which should not be shared on the website

will remove typos and improve the formatting

---

docs/bot-builder/advanced/integrating-custom-code.md

adding some more details in the title to make things clearer

making things clearer

---

docs/bot-builder/advanced/integrating-webviews-into-sdk.md

added note that only webviews with CORS enabled will work

adding note on CORS

---

docs/bot-builder/advanced/integrating-webviews-into-sdk.md

merged iOS and Android Message codes

updated message type codes

---

website/pages/en/index.js

* removed link for cordova docs

[Update] Removed Link to Cordova Support Docs

---

docs/bot-builder/advanced/integrating-custom-code.md

update the user object

---

docs/bot-builder/advanced/integrating-custom-code.md

add response for multi-lingual bot

add response for multi-lingual bot

---

docs/webhooks/meta.json
docs/webhooks/synchronous_webhooks.md

Added documentation for synchronous webhooks

added synchronous webhooks

---

docs/agent-chat/integrating-external-bot.md
docs/agent-chat/meta.json
website/i18n/en.json

Added documentation for using webhooks to use athena with an external bot

added docs for integrating with external bot on athena

---

docs/webhooks/webhook-payload.md

Added chat closing categories to the webhook event.
_**JIRA:**_
https://hello-haptik.atlassian.net/browse/PE-647

Update webhook events doc

---

docs/webhooks/webhook-payload.md

Update the closing categories from string to dictionary.

Update closing categories

---

docs/bot-builder/advanced/integrating-custom-code.md
docs/webhooks/webhook-payload.md

Sending conversation_no to custom API integration.

Update docs with new fields conversation no

---

docs/bot-builder/advanced/integrating-custom-code.md

Update Custom code section with packages list
Add default & custom packages
ADHOC

Update Custom code section with packages list

---

website/pages/en/index.js

Removed react native. As CS team assumed we support React native cos of this.

Hyperlink text updated

---

docs/webhooks/webhook-payload.md

pass chat link for webhook which are marked complete
**_JIRA:_** 
https://hello-haptik.atlassian.net/browse/PLAT-693

pass chat link in complete chats webhook

---

docs/webhooks/webhook-payload.md

update documentation for pinned chat webhook

update documentation for pinned chat webhook

---

docs/whatsapp/sending-notifications.md

Added response body 
and error body for the response for WA notifications API
ADO
Client's were asking these questions

Update sending notifications WA documentation

---

docs/bot-builder/advanced/integrating-custom-code.md
website/i18n/en.json

Update documentation for custom variables

Update documentation for custom variables

---

docs/webhooks/webhook-payload.md

webhook-conversation-complete will now get 2 more fields
Conversation data and permanent user data.

Update webhook payload docs with the new keys that will be sent

---

docs/bot-builder/integrations/integrating-apis.md

Pass env variables in payload for external integration
**_JIRA: https://hello-haptik.atlassian.net/browse/PLAT-943_**

Pass env variables in payload for external integration

---

docs/bot-analytics/sample-metrics.md
docs/other/meta.json

- Link on Sample metrics page
- Previous click on Facebook page

Broken 15 oct links

---

docs/webhooks/webhook-payload.md

pass chat link

---

docs/agent-chat/adding-custom-tools.md

update athena sdk integration, give usage

[docs][athena] update athena sdk integration

---

docs/whatsapp/technical-setup.md

Remove internal information 
TODO: add more details later.

Update Technical docs for WhatsApp

---

docs/agent-chat/adding-custom-tools.md

chat disposition for custom tools in Athena

[docs][Athena] chat disposition for custom tools

---

docs/agent-chat/adding-custom-tools.md

[docs][athena] sdk version update

---

docs/bot-builder/basic/managing-bot-state.md

Added links on using context variables in integrations and athena chat

added link to athena and integrations section

---

docs/webhooks/create-haptik-user.md
docs/webhooks/webhook-payload.md

Adding support for phone model, os version and package name

Update docs with the new params that are supported in Webhook signup

---

docs/agent-chat/adding-custom-tools.md

add setChatStatus API for athena SDK

[athena] add setChatStatus API for athena sdk

---

docs/bot-builder/integrations/integrating-custom-code.md

Added documentation for using environment variables

added environment variables

---

docs/bot-builder/integrations/additional-apis.md

modified the request type for sample CURL request for get_chat_history API

Update sample CURL command for get_chat_history

---

docs/other/security.md

Update Security We protect your data
add identity service
The last sentence did not make it clear so as to which DCs

Update Security We protect your data

---

docs/bot-builder/integrations/integration-parameters.md

Added user parameter details and device platform mappings to integration parameters section.

Add device platform info in the integration parameters section

---

docs/whatsapp/sending-notifications.md

v2 version of the API returns the WhatsApp API response directly.

Update docs for V2 of the send HSM API

---

docs/other/sla.md

Remove breach_cost_revert from SLA docs
Remove escalation Matrix from SLA docs for website
Maintaining Internal SLA doc
ADHOC -

Remove breach_cost_revert from SLA docs

---

docs/bot-builder/integrations/integrating-custom-code.md

Add information about using standard python logger inside the Code Executor

Add information on adding logs to Code Executor

---

docs/bot-builder/meta.json

Development and Testing Guidelines

---

docs/webhooks/re-enable-webhook.md

Changing the CURL command text

Update re-enable webhook

---

docs/bot-builder/integrations/additional-apis.md

Fi Typos
Jira Ticket: https://hello-haptik.atlassian.net/browse/PS-477

add backslash in url

---

docs/external-chat-tool/meta.json

The text had a case issue. Fixed in this PR.

Link change

---

docs/whatsapp/sending-notifications.md

We need to update the URL's and CURL request for Image

Update the Whatsapp Media HSM Document

---

docs/external-chat-tool/appendix.md

Update title - Appendix

---

docs/other/facebook.md

so that these steps can be used by everyone while trying to instantiate facebook bot integration

Adding steps for facebook bot integration

---

docs/external-chat-tool/security.md

- Fix a few errors in the request format
- Add a few notes to clarify things

Update docs to fix errors in tract security doc

---

docs/whatsapp/sending-notifications.md

Reolving bugs associated with the markdown syntax

---

docs/webhooks/create-haptik-user.md

- The page title section syntax was slightly incorrect which lead to a bad looking page. Correcting that

Correcting a minor mistake with the page title section

---

docs/external-chat-tool/security.md

- Provide sample python code
- Detail the process of signature generation
- Add warnings

Provide disambiguation info signing TRACT requests

---

docs/agent-chat/agent-reports.md
docs/agent-chat/meta.json

Agent Reports documentation
@nikunj1705

Agent Reports documentation

---

website/config/generate.js

- Updated side bar to handle subcategories
[example](http://devsampras.hellohaptik.com:3000/whatsapp) for subcategory

Update generate sidebar function to account for subcategories

---

docs/android-sdk/extension-module-integration.md
docs/android-sdk/image-loading-modules.md
docs/android-sdk/index.md
docs/android-sdk/integrating-jio-communications-module.md
docs/android-sdk/migrating-from-earlier-versions.md
docs/android-sdk/xdk-module-integration.md

Updated docs with new Android SDK

Updated docs with new Android SDK

---

docs/ios-sdk/index.md

SDK version updated

---

docs/android-sdk/extension-module-integration.md
docs/android-sdk/image-loading-modules.md
docs/android-sdk/index.md
docs/android-sdk/integrating-jio-communications-module.md
docs/android-sdk/migrating-from-earlier-versions.md
docs/android-sdk/xdk-module-integration.md

- Version numbers for the dependencies have now been changed to v6.5.2
CIA-6422

Update the documentation for latest Android SDK release

---

docs/agent-chat/agent-reports.md

Added Avg Response Time Weights to the agent reports

Added Avg Response Time Weights to the agent reports

---

docs/bot-builder/integrations/additional-apis.md

https://hello-haptik.atlassian.net/browse/AGCT-341

Add countdown params to external chat to agent API

---

docs/bot-builder/integrations/additional-apis.md

Updating countdown description copy of external chat to queue API

updating countdown copy

---

docs/bot-builder/integrations/additional-apis.md

Added range to countdown description

Added range to countdown description

---

docs/android-sdk/extension-module-integration.md
docs/android-sdk/image-loading-modules.md
docs/android-sdk/index.md
docs/android-sdk/integrating-jio-communications-module.md
docs/android-sdk/migrating-from-earlier-versions.md
docs/android-sdk/xdk-module-integration.md

- Update the Haptik Android SDK version in the documentation
CIA-6556

Update the Android SDK version in documentation

---

docs/web-sdk/support-native.md

Added documentation to properly support XDK in WebViews

Added documentation to properly support XDK in WebViews

---

docs/web-sdk/configuration-sdk-methods.md

Added logout method doc

---

docs/web-sdk/configuration-customisation.md
docs/web-sdk/configuration-sdk-methods.md

Added doc for privacy policy URL setting

Added doc for privacy policy URL setting

---

docs/webhooks/webhook-payload.md

update `webhook_conversation_complete` documentation
added `agent_details` and `follow_up_details`

Update Documentation for webhook_conversation_complete event

---

docs/external-chat-tool/appendix.md

- rename an event category
- update hooks list url to include /tract

Update tract docs to avoid common confusions

---

docs/webhooks/webhook-payload.md

- add collection details to `webhook_conversation_complete` 
- add conversation identifier

Add collection details to webhook

---

docs/agent-chat/chat-assignment.md

Ticket: https://hello-haptik.atlassian.net/browse/AGCT-532
Note:
1. If you have a single client and multiple businesses set up, all businesses must be the same algorithm
2. If you have multiple client setup, one can ideally have different algorithms for both, provided there are no shared agents between the two clients.

Chat Assignment Usage Notes

---

docs/web-sdk/configuration-sdk-methods.md

Added docs for language picker

Added docs for language picker

---

docs/webhooks/meta.json
docs/webhooks/send-feedback-to-haptik.md
docs/webhooks/send-file-to-haptik.md
docs/webhooks/send-message-to-haptik.md

- Add guidelines for clients using Bot as API to send feedback to Haptik API
CIA-6688

Add documentation to enable clients using Bot as API to send feedback to Haptik API

---

docs/agent-chat/chat-assignment.md

https://hello-haptik.atlassian.net/browse/AGCT-581

Chat assignment, difference

---

docs/android-sdk/extension-module-integration.md
docs/android-sdk/image-loading-modules.md
docs/android-sdk/index.md
docs/android-sdk/integrating-jio-communications-module.md
docs/android-sdk/migrating-from-earlier-versions.md
docs/android-sdk/xdk-module-integration.md

- Publish documentation for Android SDK v7.0.0

Publish documentation for latest version of Android SDK

---

docs/bot-builder/basic/user-says-guidelines.md
docs/bot-builder/basic/user-says.md

Removing Synonyms documentation

Shrey4500 patch 2

---

docs/bot-builder/integrations/additional-apis.md

https://hello-haptik.atlassian.net/browse/AGCT-751

Chat Transcript V2 api information

---

docs/bot-builder/integrations/integrating-custom-code.md

update conversation variable size limit from 500 to 2500

update conversation variable size limit

---

docs/android-sdk/index.md

- Add documentation to help client implement InitDataCallback for Haptik Android SDK

 Add documentation for InitDataCallback

---

docs/bot-builder/basic/multiple-languages.md

languages now support person name entity as well

person name is now supported

---

docs/bot-builder/basic/chat-elements.md

Update buttons and forms (chat elements)

---

docs/bot-builder/basic/chat-elements.md

forms now have support in multiple languages

add info that chatforms are supported in multiple languages

---

docs/external-chat-tool/meta.json
docs/external-chat-tool/thread-control.md

- Talk about TRACT TC in multi chat tool scenarios
https://hello-haptik.atlassian.net/browse/AGCT-870

docs(TRACT): Add thread control docs

---

docs/agent-chat/claiming-and-closing.md

Updating the rules w.r.t user and agent relation

---

docs/bot-builder/basic/bot-says.md
docs/bot-builder/basic/entities.md
docs/bot-builder/integrations/additional-apis.md
docs/bot-builder/integrations/integrating-custom-code.md
docs/whatsapp/types-of-conversations.md

EGM tickets

---

docs/android-sdk/extension-module-integration.md
docs/android-sdk/image-loading-modules.md
docs/android-sdk/index.md
docs/android-sdk/integrating-jio-communications-module.md
docs/android-sdk/migrating-from-earlier-versions.md
docs/android-sdk/xdk-module-integration.md

Updated android SDK docs for new release

Updated android SDK docs for new release

---

docs/agent-chat/chat-assignment.md

https://hello-haptik.atlassian.net/browse/AGCT-274
https://hello-haptik.atlassian.net/browse/AGCT-1086

Balanced Distribution, Shared Agents support

---

docs/bot-builder/advanced/integrating-with-external-bot.md
docs/webhooks/webhook-payload.md

Cleanup (int, adv, webhook) EGM-463

---

docs/bot-analytics/using-message-analysis.md

Update Message Analysis

---

docs/agent-chat/adding-custom-tools.md
docs/agent-chat/bot-agent-handover.md
docs/agent-chat/claiming-and-closing.md
docs/agent-chat/closing-categories.md
docs/agent-chat/index.md
docs/agent-chat/newmychats.md
docs/agent-chat/teams.md

EGM-387 update SAC sidebar

---

docs/bot-analytics/word-analysis.md

Word Analysis changes

---

docs/bot-builder/basic/business.md
docs/bot-builder/basic/dialoguemanager.md
docs/bot-builder/basic/platforms-deployment.md
docs/bot-builder/basic/sharebot.md
docs/bot-builder/basic/transferbot.md

Clean up - NLU, Config, HSL (EGM-458)

---

docs/bot-analytics/chat-links.md

Update Chat Link for Data Masking

---

docs/facebook/admin-deploy.md
docs/facebook/cs-fb.md
docs/facebook/index.md
docs/facebook/meta.json
docs/facebook/technical-setup.md
website/pages/en/index.js

Facebook Self-Serve

---

docs/salesforce/build-integration.md
docs/salesforce/build-laa.md
docs/salesforce/index.md
docs/salesforce/meta.json
docs/salesforce/setup-laa.md
docs/salesforce/setup-ti.md

Salesforce Integration doc

---

docs/webhooks/meta.json

New BotAPI Structure

---

docs/agent-chat/smart-actions.md

removing one word.
https://hello-haptik.atlassian.net/browse/AGCT-1166

No support uploading .docx files as attachments

---

docs/android-sdk/extension-module-integration.md
docs/android-sdk/image-loading-modules.md
docs/android-sdk/index.md
docs/android-sdk/integrating-jio-communications-module.md
docs/android-sdk/migrating-from-earlier-versions.md
docs/android-sdk/xdk-module-integration.md

- Update the documentation with changes for the latest Android SDK

Update the documents with the latest release of Android SDK

---

docs/shopify/build-shopify.md
docs/shopify/index.md
docs/shopify/meta.json
docs/shopify/setup-shopify.md
website/pages/en/index.js

Shopify Documentation

---

docs/zendesk/index.md
docs/zendesk/meta.json
docs/zendesk/sunshine.md
docs/zendesk/zenchat.md
docs/zendesk/zendesk-ui.md
website/pages/en/index.js

Zendesk Documentation 2

---

docs/bot-builder/basic/multiple-languages.md

Auto-Detect User Language- 504

---

docs/zendesk/sunshine.md

Update sunco image

---

docs/android-sdk/extension-module-integration.md
docs/android-sdk/image-loading-modules.md
docs/android-sdk/index.md
docs/android-sdk/integrating-jio-communications-module.md
docs/android-sdk/migrating-from-earlier-versions.md
docs/android-sdk/xdk-module-integration.md

Updated Android SDK v7.1.0 docs

Updated Android SDK v7.1.0 docs

---

docs/zendesk/sunshine.md

Update sunco image - final

---

docs/bot-analytics/overview.md

Conversation Split

---

docs/bot-analytics/index.md
docs/bot-analytics/overview.md

EGM-521 Overview changes

---

docs/bot-analytics/overview.md

Conversation Split final

---

docs/bot-analytics/user-ratings.md
docs/bot-analytics/user-reviews.md
docs/bot-analytics/using-message-analysis.md

Ratings/Reviews/Output Node

---

docs/bot-builder/basic/qa-best-practices.md

EGM-486 QA PPT

---

docs/agent-chat/adding-user-details.md

Adding User details - 505

---

docs/bot-analytics/analytics-reports.md

Reporting in Analytics

---

docs/bot-builder/basic/entities.md
docs/hsl/button.md

Upload PDF HSl and File MB

---

docs/bot-builder/basic/bot-prompt-trigger.md

Dynamic bot prompt triggers

---

docs/whatsapp/index.md

Update information regarding WA link

---

docs/agent-chat/analytics.md

Update report duration

---

website/pages/en/index.js

Update Salesforce Service Cloud Integration name

---

docs/bot-builder/basic/entities.md

Update entity flusher

---

docs/bot-builder/integrations/integrating-custom-code.md
docs/web-sdk/feature-user-signup.md

Updating custom sign up

---

docs/agent-chat/raw-chat-links.md

Raw Chat Links Documentation

---

docs/agent-chat/adding-user-details.md
docs/agent-chat/meta.json
docs/agent-chat/right-hs.md

Adding user details in index

---

docs/zendesk/meta.json

Update Zendesk Index

---

docs/bot-builder/basic/entities.md

Add entity playlist

---

docs/telegram/build-bot.md
docs/telegram/index.md
docs/telegram/meta.json
docs/telegram/setup-telegram.md
docs/telegram/telegram-ui.md
website/pages/en/index.js

Telegram documentation

---

docs/bot-builder/basic/assets/tsvuploader.tsv
docs/bot-builder/basic/general-nodes.md
docs/webhooks/index.md

Update TSV file and BOT API

---

docs/bot-builder/basic/bot-prompt-trigger.md

Update Bot Prompt

---

docs/agent-chat/sac-faq.md
docs/bot-analytics/analytics-faqs.md
docs/bot-builder/basic/faqs-cs.md
docs/bot-builder/meta.json

FAQs on CS, SAC, IA

---

docs/agent-chat/bot-agent-handover.md
docs/agent-chat/businesses.md
docs/agent-chat/meta.json
docs/agent-chat/sac-faq.md

EGM-540 - Claiming and Closing chats cleanup

---

docs/agent-chat/sac-faq.md

SAC FAQ update

---

docs/zendesk/zendesk-ui.md

Sunco supports location

---

docs/teams/index.md
docs/teams/meta.json
docs/teams/on-cs.md
docs/teams/setup-teams.md
website/pages/en/index.js

Microsoft Teams Doc
